version: '2'
services:
    nginx:
        image: 'wazo/nginx-ssl:latest'
        ports:
        - "443:443"
        volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
    wazo-auth:
        image: 'wazoplatform/wazo-auth-mock'
        command: ["/usr/local/bin/wazo-auth-mock.py", "9497", "/api/auth"]